import { useEffect, useState } from 'react';
import { generateClientSummary, getLatestClientSummary } from '../services/aiService';

function formatDate(value) {
  if (!value) return '—';
  return new Date(value).toLocaleString();
}

function sentimentClasses(sentiment) {
  switch (sentiment) {
    case 'Positive':
      return 'bg-green-100 text-green-700';
    case 'Negative':
      return 'bg-red-100 text-red-700';
    case 'Mixed':
      return 'bg-yellow-100 text-yellow-700';
    default:
      return 'bg-gray-100 text-gray-600';
  }
}

export default function ClientSummaryPanel({ clientId }) {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    getLatestClientSummary(clientId)
      .then((data) => {
        if (!cancelled) setSummary(data);
      })
      .catch((err) => {
        // A 404 here just means no summary has been generated yet — not
        // an error state, so it's not shown as one.
        if (!cancelled && err.response?.status !== 404) {
          setError('Could not load the latest summary.');
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [clientId]);

  const handleGenerate = async () => {
    setError('');
    setGenerating(true);
    try {
      const data = await generateClientSummary(clientId);
      setSummary(data);
    } catch (err) {
      setError(err.response?.data?.message || 'Could not generate a summary right now.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="rounded-lg border border-gray-200 bg-white p-5">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h2 className="text-sm font-semibold text-gray-900">Client Summary</h2>
          {summary && (
            <p className="mt-1 text-xs text-gray-500">
              Generated by {summary.generatedByName} • {formatDate(summary.generatedAt)}
            </p>
          )}
        </div>
        <button
          type="button"
          onClick={handleGenerate}
          disabled={generating}
          className="shrink-0 rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-60"
        >
          {generating ? 'Generating…' : 'Generate Client Summary'}
        </button>
      </div>

      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

      {loading && <p className="mt-4 text-sm text-gray-500">Loading summary…</p>}

      {!loading && !summary && !error && (
        <p className="mt-4 text-sm text-gray-500">
          No summary has been generated yet. Click "Generate Client Summary" to create one from this
          client's uploaded documents.
        </p>
      )}

      {generating && (
        <p className="mt-4 text-sm text-gray-500">
          Reading this client's documents and generating a summary…
        </p>
      )}

      {!generating && summary && (
        <div className="mt-4 space-y-4">
          <div className="flex flex-wrap items-center gap-2">
            <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${sentimentClasses(summary.sentiment)}`}>
              Sentiment: {summary.sentiment}
            </span>
            {summary.attentionRequired && (
              <span className="rounded-full bg-red-100 px-2.5 py-1 text-xs font-medium text-red-700">
                ⚠ Attention required
              </span>
            )}
          </div>

          {summary.attentionRequired && summary.attentionReason && (
            <p className="text-sm text-red-700">{summary.attentionReason}</p>
          )}

          <SummarySection title="Current Situation" text={summary.currentSituation} />

          {summary.majorProblems?.length > 0 && (
            <div>
              <h3 className="text-xs font-medium uppercase tracking-wide text-gray-500">Major Problems</h3>
              <ul className="mt-1 list-inside list-disc space-y-1 text-sm text-gray-700">
                {summary.majorProblems.map((problem, index) => (
                  <li key={index}>{problem}</li>
                ))}
              </ul>
            </div>
          )}

          <SummarySection title="Recent Activity" text={summary.recentActivity} />
        </div>
      )}
    </div>
  );
}

function SummarySection({ title, text }) {
  if (!text) return null;
  return (
    <div>
      <h3 className="text-xs font-medium uppercase tracking-wide text-gray-500">{title}</h3>
      <p className="mt-1 text-sm text-gray-700">{text}</p>
    </div>
  );
}
